#PAS FINALISE
# A déclarer :
#     - SERVICE : nom du service
#     - DATA_LOCATION : localisation des données (exemple /apps/"service")
#     - NDD : lien du nom de domaine (exemple : papamica.fr)
#     - DB_USER : nom d'utilisateur pour la base de données
#     - DB_PASSWORD : mot de passe pour la base de données
#     - DB_ROOT : mot de passe ROOT pour la base de données
#     - DATA : localisation de vos fichiers à explorer


version: "2.1"
services:
  wikijs:
    image: ghcr.io/linuxserver/wikijs
    container_name: wikijs
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - $DATA_LOCATION/config:/config
      - $DATA_LOCATION/data:/data
    ports:
      - 3000:3000
    restart: unless-stopped
    depends_on:
      - postgres-server
    # Facultatif  
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.$SERVICE.entrypoints=http"
      - "traefik.http.routers.$SERVICE.rule=Host(`$SERVICE.$NDD`)"
      - "traefik.http.middlewares.$SERVICE-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.$SERVICE.middlewares=$SERVICE-https-redirect"
      - "traefik.http.routers.$SERVICE-secure.entrypoints=https"
      - "traefik.http.routers.$SERVICE-secure.rule=Host(`$SERVICE.$NDD`)"
      - "traefik.http.routers.$SERVICE-secure.tls=true"
      - "traefik.docker.network=proxy"
 # Base de données
  wikijs_db:
  # Base de données
  postgres-server:    # The Postgres Database Service
    image: postgres:13.1
    restart: always
    container_name: $SERVICE-db
    environment:   # Username, password and database name variables
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: wikijs
      PG_DATA: /var/lib/postgresql/data/pgdata #data storage
    volumes:
      - $DATA_LOCATION/db:/var/lib/postgresql/data

    # Facultatif  
    networks:
      - proxy
networks:
  proxy:
    external:
      name: proxy
