# Variables à déclarer :
#     - SERVICE : nom du service
#     - DATA_LOCATION : localisation des données
#     - NDD : lien du nom de domaine
#     - DB_USER : nom d'utilisateur pour la base de données
#     - DB_PASSWORD : mot de passe pour la base de données


version: "2"
services:
  # Base de données
  postgres-server:  
    image: postgres:13.2
    restart: always
    container_name: $SERVICE-db
    environment:  
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: zabbix
      PG_DATA: /var/lib/postgresql/data/pgdata
    volumes:
      - $DATA_LOCATION/db:/var/lib/postgresql/data

    # Facultatif  
    networks:
      - proxy
 
  zabbix-server:  # Zabbix main component
    image: zabbix/zabbix-server-pgsql:ubuntu-5.2.5
    restart: always
    container_name: $SERVICE-server
    environment:   
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: zabbix
      ZBX_HISTORYSTORAGETYPES: log,text 
      ZBX_DEBUGLEVEL: 1
      ZBX_HOUSEKEEPINGFREQUENCY: 1
      ZBX_MAXHOUSEKEEPERDELETE: 5000
      ZBX_STARTVMWARECOLLECTORS: 10
      ZBX_VMWAREFREQUENCY: 30
      ZBX_VMWAREPERFFREQUENCY: 30
      ZBX_VMWARECACHESIZE: 16M
      ZBX_VMWARETIMEOUT: 10
    depends_on:
      - postgres-server
    ports:
      - 10051:10051
    volumes:  #Scripts
      - $DATA_LOCATION/alertscripts:/usr/lib/zabbix/alertscripts

    # Facultatif  
    networks:
      - proxy

  zabbix-web:    # Web UI
    image: zabbix/zabbix-web-nginx-pgsql:ubuntu-5.2.5
    restart: always
    container_name: $SERVICE-web
    environment: 
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: zabbix
      ZBX_SERVER_HOST: zabbix-server
      ZBX_POSTMAXSIZE: 64M
      PHP_TZ: "Europe/Paris"
      ZBX_MAXEXECUTIONTIME: 500
    depends_on:
      - postgres-server
      - zabbix-server
#    ports:    # Port where Zabbix UI is available
#      - 8090:8080

    # Facultatif
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.$SERVICE.entrypoints=http"
      - "traefik.http.routers.$SERVICE.rule=Host(`$SERVICE.$NDD`)"
      - "traefik.http.middlewares.$SERVICE-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.$SERVICE.middlewares=$SERVICE-https-redirect"
      - "traefik.http.routers.$SERVICE.middlewares=hsts-headers@file"
      - "traefik.http.routers.$SERVICE-secure.entrypoints=https"
      - "traefik.http.routers.$SERVICE-secure.rule=Host(`$SERVICE.$NDD`)"
      - "traefik.http.routers.$SERVICE-secure.middlewares=hsts-headers@file"
      - "traefik.http.routers.$SERVICE-secure.tls=true"
# Uncomment this if not using pre-existant certificate
#      - "traefik.http.routers.$SERVICE-secure.tls.certresolver=http"
      - "traefik.http.services.$SERVICE-secure.loadbalancer.server.port=8080"
      - "traefik.docker.network=proxy"
      
networks:
  proxy:
    external:
      name: proxy
