version: "3.2"
services:
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - /home/debian/torrent/rtorrent/downloads/Alexis/Configs/Jackett:/config
      - /home/debian/torrent/rtorrent/downloads/Alexis/Torrents:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - UMASK_SET=022 #optional
    volumes:
      - /home/debian/torrent/rtorrent/downloads/Alexis/Configs/Radarr:/config
      - /home/debian/torrent/rtorrent/downloads/Alexis/series:/movies
      - /home/debian/torrent/rtorrent/downloads/Alexis/Torrents:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  sabnzbd:
    image: ghcr.io/linuxserver/sabnzbd
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - /home/debian/torrent/rtorrent/downloads/Alexis/Configs/Sabnzbd:/config
      - /home/debian/torrent/rtorrent/downloads/Alexis/Downloads:/downloads
      - /home/debian/torrent/rtorrent/downloads/Alexis/Downloads/Incomplete:/incomplete-downloads #optional
    ports:
      - 8181:8080
      - 9191:9090
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - UMASK_SET=022
    volumes:
      - /home/debian/torrent/rtorrent/downloads/Alexis/Configs/Sonarr:/config
      - /home/debian/torrent/rtorrent/downloads/Alexis/series:/tv
      - /home/debian/torrent/rtorrent/downloads/Alexis/Torrents:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=harvester
      - HARVESTER_ENDPOINT=https://127.0.0.1:5000/token
      - TZ=Europe/Paris
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped
    
  deluge:
    image: ghcr.io/linuxserver/deluge
    container_name: deluge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - /home/debian/torrent/rtorrent/downloads/Alexis/Configs/Deluge:/config
      - /home/debian/torrent/rtorrent/downloads/Alexis/Downloads:/downloads
      - /home/debian/torrent/rtorrent/downloads/Alexis/series:/series
      - /home/debian/torrent/rtorrent/downloads/Alexis/films:/films
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    
  overseerr:
    image: ghcr.io/linuxserver/overseerr
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - /home/debian/torrent/rtorrent/downloads/Alexis/Configs/overseer:/config
    ports:
      - 5055:5055
    restart: unless-stopped
