version: '3'
services:
  zabbix-proxy:  
    image: zabbix/zabbix-proxy-sqlite3:ubuntu-5.2.5 #edit the version to the latest version available (not latest tag)
    restart: always
    container_name: proxy-zabbix
    volumes:
      - /apps/zabbix-proxy/:/var/lib/zabbix/enc/:ro #mount the psk file for encryption, optionnal
    environment:  
      ZBX_PROXYMODE: 0
      ZBX_HOSTNAME: HOSTNAME OF THIS PROXY (must match on zabbix server when adding this proxy)
      ZBX_SERVER_HOST: IP or DNSNAME of ZABBIX SERVER
      ZBX_ENABLEREMOTECOMMANDS: 1
      ZBX_STARTPINGERS: 1
      ZBX_STARTPOLLERS: 5
      ZBX_IPMIPOLLERS: 1
      ZBX_STARTPOLLERSUNREACHABLE: 1
      ZBX_STARTTRAPPERS: 5
      ZBX_STARTDISCOVERERS: 1
      ZBX_STARTHTTPPOLLERS: 1
      ZBX_STARTVMWARECOLLECTORS: 10
      ZBX_VMWAREFREQUENCY: 60
      ZBX_VMWAREPERFFREQUENCY: 60
      ZBX_VMWARECACHESIZE: 8M
      ZBX_VMWARETIMEOUT: 10
      ZBX_TLSCONNECT: psk # Encryption, optionnal
      ZBX_TLSACCEPT: psk # Encryption, optionnal
      ZBX_TLSPSKIDENTITY: homelab # Encryption, optionnal
      ZBX_TLSPSKFILE: zabbix_proxy.psk # Encryption, optionnal
    ports:
      - 10051:10051 # Active port
